kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: multibooru-entity-data
  namespace: imageboards
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi